# This workflow will build and push official docker images for Noetic/Foxy OS when new push occurs 
# to develop, master, release branches but doesn't run any unit test or sonar scanner
name: Docker Hub Noetic/Foxy build
on:
  push:
    branches:
      - develop
      - master
      - "release/*"
    tags:
      - "carma-system-*"
    paths:
      - '**'  # Build when there are changes in noetic-foxy folder or related files
      - '!humble/**' # Exclude humble folder
jobs:
  # Noetic/Foxy 20.04 (ROS1 Noetic/ ROS2 Foxy)
  dockerhub-noetic-foxy:
    uses: usdot-fhwa-stol/actions/.github/workflows/dockerhub.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      file: ./noetic-foxy/Dockerfile
      # TODO: add noetic-foxy suffix when humble is migrated 
      #tag_name_suffix: noetic-foxy https://usdot-carma.atlassian.net/browse/ARC-227