# This workflow will only build for Pull Requests which are opened, changed , merged 
# that has changes in noetic-foxy folder or related files 
name: Docker Noetic/Foxy build
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**'
      - '!humble/**' # Exclude humble folder
jobs:
  # Noetic/Foxy 20.04 (ROS1 Noetic/ ROS2 Foxy)
  docker-build-noetic-foxy:
    uses: usdot-fhwa-stol/actions/.github/workflows/docker.yml@main
    with:
      file: ./noetic-foxy/Dockerfile
